# render.yaml
services:
  - type: web
    name: hottiyya
    region: oregon
    plan: free
    env: python
    # أمر بناء واحد فقط يشغل السكربت
    buildCommand: chmod +x render-build.sh && ./render-build.sh
    startCommand: gunicorn -w 4 -k uvicorn.workers.UvicornWorker main:app
    envVars:
      - key: SECRET_KEY
        generateValue: true # الطريقة الصحيحة لتوليد مفتاح سري في Render